services:
  server:
    build: ./server
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - "8000:8000"
  client:
    build: ./client
    command: yarn start
    volumes:
      - .:/client
    ports:
      - "3000:3000"
    depends_on:
      - server